### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#1]
As a site user
I can view a navbar from every page
So that I can navigate easily between pages

## Acceptance Criteria
- Navbar should persist on every page
- Navbar should contain the following: logo, sign in/out, quizzes, popular quizzes and create quiz
- Navbar should contain 'sign up' if user is not logged
- Navbar should make it clear whether user is logged in
- Navbar should highlight the relevant page that the user is on
- Links should change colour when a user hovers over them

## Tasks
- [x] Create NavBar component
- [x] Add 'loggedIn' and 'loggedOut' navlinks to component
- [x] Add css module and styles
