### ISSUE TITLE
USER STORY: Quizzes Page

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#10]
As a site user
I can see all the available quizzes
So that I can choose which one I want to do

## Acceptance Criteria
- Quizzes should be displayed on the home page
- All quizzes should load by default
- Quizzes should have an image to show their category, a title, and a description

## Tasks
- [x] Add QuizzesPage component
- [x] Add routes for different filters
- [x] Add JSX to QuizzesPage return
- [x] Add fetchQuizzes function
- [x] Create QuizTile component
- [x] Add links to QuizTiles
