### ISSUE TITLE
USER STORY: Infinite Scroll

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#11]
As a site user
I can keep scrolling through the available quizzes that are loaded for me automatically
So that I don't have to click on "next page" etc

## Acceptance Criteria
Quizzes page should implement an infinite scroll so that quizzes continue to load as a user scrolls

## Tasks
- [x] Install infinite scroll package
- [x] Add component to quizzes page
- [x] Add css styling to break into columns
