### ISSUE TITLE
USER STORY: Quiz search

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#12]
As a site user
I can search the quizzes using keywords
So that I can find specific quizzes

## Acceptance Criteria
- Quizzes page should contain a search bar at the top of the screen
- Search bar should search based on text input without a user needing to press enter
- A 'loading' indicator should be shown whilst search results are retrieved

## Tasks
- [x] Add jsx for search bar
- [x] Add asset for loading spinner to jsx
- [x] Add search filter to API request
