### ISSUE TITLE
USER STORY: Quiz Filters

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#13]
As a site user
I can filter quizzes by category
So that I can find quizzes in categories that interest me

## Acceptance Criteria
- The quizzes page should contain 3 buttons for filtering: Sport, Music/Entertainment, General Knowledge
- When a user selects a filter button, it should filter the quizzes by that category
- A 'loading' indicator should be shown whilst filter results are retrieved

## Tasks
- [x] Add routes for relevant category filters
- [x] Add buttons for category filters to Quizzes page
- [x] Add asset spinner to jsx
- [x] Add category filter to API request
