### ISSUE TITLE
USER STORY: Play State Timer

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#15]
As a site user
I can start a quiz
So that I can begin a countdown timer for my responses

## Acceptance Criteria
- When a user presses the 'start quiz' button, a timer should start counting down to indicate the quiz has started
- The guess input box should become active when the quiz has started
- The timer should be reset if the user refreshes the page
- If a user completes the quiz before the timer runs out, the timer should pause
- If the timer runs out before the quiz is completed, it should change to a button that says "Reset"
- Pressing the "Reset" button should refresh the quiz and the timer back to the beginning

## Tasks
- [x] Add timer component
- [x] Add timer countdown function
- [x] Add buttons for controlling quiz state
- [x] Add functions to handle guess and check for quiz completion
