### ISSUE TITLE
USER STORY: Play State Missing Answers

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#18]
As a site user
I can see the answers to the quiz once the timer ends
So I can see any that I missed

## Acceptance Criteria
- Users should be shown any answers they did not get when the timer runs out
- Answers that the user did not get should be shown in a different colour

## Tasks
- [x] Add handleGiveUp function to reveal answers
- [x] Add Styling to answers that weren't guessed
- [x] Add check to useEffect that reveals answers when timer runs out
