### ISSUE TITLE
USER STORY: Delete Quiz

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#23]
As a logged in site user
I can delete any quizzes I have created
So that I can control the content I have provided

## Acceptance Criteria
- If a user is on a quiz that they created, they should given an icon that allows them to delete the quiz
- If a user selects the delete icon, it should delete the quiz from the database
- The user should be prompted to confirm that they want to delete the quiz

## Tasks
- [x] Add MoreDropdown component
- [x] Add dropdown component to quiz page
- [x] Add Delete function to quiz page 
- [x] Add QuizEditForm
- [x] Add modal with message that confirms deletion
