### ISSUE TITLE
USER STORY: Fastest Times

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#24]
As a logged in user
I can see my fastest time on any quizzes I have completed
So that I know how quickly I have previously completed a quiz

## Acceptance Criteria
- If a logged in user completes a quiz before the time limit runs out, a fastest time record should be created for that user and that quiz
- If a logged in user is on a quiz that they have completed, they should be able to see their fastest time

## Tasks
- [x] Add handleCompleted function to check if a user has guessed all answers
- [x] Add handleCreateScore function to make a post request to create a score
- [x] Add ternary check to JSX to output score if user has completed the quiz
