### ISSUE TITLE
USER STORY: Like a quiz

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#27]
As a logged in user
I can like a quiz
So that I can show my support for the quizzes that interest me

## Acceptance Criteria
- Logged in users should be able to select a 'like' button on the quiz page
- The like button should show how many likes the quiz currently has
- When a user selects the like button the number of likes should increase by 1
- The like button should give the user feedback to show that it has been selected
- If a user is not logged in they should be given feedback that they need to login in to like a quiz

## Tasks
- [x] Add jsx for likes button
- [x] Add logic to jsx to change like button depending on user type
- [x] Add functions to handle a like
- [x] Add styling to button
