### ISSUE TITLE
USER STORY: Create a comment

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#29]
As a logged in user
I can add comments to a quiz
So that I can share my thoughts about the quiz

## Acceptance Criteria
- Logged in users should be able to see a comment form below each quiz
- Logged out users should not be able to see a comment form
- Logged in users should be able to enter a comment into the form and press a button to submit their comment

## Tasks
- [x] Add CommentCreateForm.js
- [x] Add function for submitting a comment
- [x] Add styling to the component
- [x] Add comment component
- [x] Add JSX for displaying comment component on QuizPage
- [x] Add styling for comment component
