### ISSUE TITLE
USER STORY: Sign Up

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#3]
As a site user
I can create a new account 
So that I can access all the features for signed up users

## Acceptance Criteria
- Registration should require user to select a username and password
- User should be required to create a unique username
- User should be able to get to the registration process from the navigation bar
- Registration form should match the style of the website

## Tasks
- [x] Install axios and add axios defaults
- [x] Create signup form component
- [x] Add signup form css module and styles
- [x] Add signup form change handler
- [x] Add API call for submitting form
