### ISSUE TITLE
USER STORY: Delete comments

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#32]
As an owner of a comment
I can delete my comment
So that I can control removal of my comment from the application

## Acceptance Criteria
- Logged in users should be able to select a delete button on any comments they have made
- The delete button should remove the comment from the page and the database

## Tasks
- [x] Add handleDelete function to Comment component
- [x] Add delete button to dropdown menu
- [x] Link handleDelete to delete button
- [x] Update current array of comments when a comment is deleted
