### ISSUE TITLE
USER STORY: Edit a comment

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#33]
As an owner of a comment
I can edit my comment
So that I can fix or update my existing comment

## Acceptance Criteria
- Logged in users should be able to select an edit button on any comments they have made
- The edit button should reveal a comment form that allows them to edit the existing content
- Users should be able to cancel the edit
- Users should be able to submit the edit and instantly see their updated comment

## Tasks
- [x] Add CommentEdit form 
- [x] Add handleSubmit function to CommentEdit form
- [x] Add edit button to dropdown menu
- [x] Update current array of comments when a comment is edited
- [x] Add conditional check for showing edit form in Comment JSX
