### ISSUE TITLE
USER STORY: Sign In

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#4]
As a site user
I can sign in to the app
So that I can access functionality for logged in users

## Acceptance Criteria
- Users should have a separate screen for logging into the site, accessible via the navigation bar
- Users should be able to enter their username and password and submit this for login
- Login form should match the style of the website

## Tasks
- [x] Create sign in form component
- [x] Add sign in form css module
- [x] Add handle change function
- [x] Add handle submit function
- [x] Add currentUser context
