### ISSUE TITLE
USER STORY: Edit Profile

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#8]
As a logged in site user
I can see and edit my own profile
So that I can change my bio

## Acceptance Criteria
- Users should be able to access their own profile from the Navbar and be taken to a separate page for their profile
- Users should be able to see their: username, bio, quizzes created, quizzes completed
- Users should be able to edit and save their bio information
- User should be given feedback that their change has been made

## Tasks
- [x] Create ProfileEditForm
- [x] Add route for ProfileEditForm
- [x] Add function to prepopulate form data
- [x] Add function to submit updated data
- [x] Redirect user to profile page
- [x] Add modal with edit confirmation message
