### ISSUE TITLE
USER STORY: Update Username and Password

### ISSUE THREAD

**Issue by adamhatton** [adamhatton/quizle#9]
As a logged in site user
I can update my username and password
So that I can change my display name and keep my profile secure

## Acceptance Criteria
- Users should be able to edit and save their username
- Users should be able to edit and save their password
- User should be given feedback about any changes they have made

## Tasks
- [x] Add UsernameForm
- [x] Add UserPasswordForm
- [x] Add routes for new forms
- [x] Add jsx for structure of forms
- [x] Add function for submitting forms
- [x] Add modal with edit confirmation message
